{{ $ca := genCA "kubesec-webhook-ca" 365 }}
{{ $cn := printf "kubesec-webhook.%s.svc.cluster.local" .Release.Namespace }}
{{ $altNames := list ( printf "kubesec-webhook.%s.svc" .Release.Namespace ) -}}
{{ $server := genSignedCert $cn nil $altNames 365 $ca }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubesec-webhook.fullname" . }}
type: Opaque
data:
  {{- if .Values.server.certData }}
  cert.pem: {{ .Values.server.certData }}
  {{- else }}
  cert.pem: {{ b64enc $server.Cert }}
  {{- end }}
  {{- if .Values.server.caKeyData }}
  key.pem: {{ .Values.server.caKeyData }}
  {{- else }}
  key.pem: {{ b64enc $server.Key }}
  {{ end }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: kubesec-webhook
  labels:
    app: kubesec-webhook
    kind: validator
webhooks:
  - name: admission.kubesec.io
    clientConfig:
      service:
        name: kubesec-webhook
        namespace: kubesec
        path: "/"
  {{- if .Values.server.caData }}
      caBundle: {{ .Values.server.caData }}
  {{- else }}
      caBundle: {{ b64enc $ca.Cert }}
  {{- end }}
    rules:
  {{- if .Values.config.validate.daemonsets }}
      - operations:
        - CREATE
        - UPDATE
        apiGroups:
        - apps
        apiVersions:
        - "*"
        resources:
        - daemonsets
  {{- end }}
  {{- if .Values.config.validate.deployments }}
      - operations:
        - CREATE
        - UPDATE
        apiGroups:
        - apps
        apiVersions:
        - "*"
        resources:
        - deployments
  {{- end }}
  {{- if .Values.config.validate.pods }}
      - operations:
        - CREATE
        - UPDATE
        apiGroups:
        - ""
        apiVersions:
        - "v1"
        resources:
        - pods
  {{- end }}
  {{- if .Values.config.validate.statefulsets }}
      - operations:
        - CREATE
        - UPDATE
        apiGroups:
        - apps
        apiVersions:
        - "*"
        resources:
        - statefulsets
  {{- end }}
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        kubesec-validation: enabled
    sideEffects: None
    timeoutSeconds: 15
    admissionReviewVersions: ["v1"]
